# Car Evaluation

Link: https://archive.ics.uci.edu/dataset/19/car+evaluation



## 1. Información General

* **Creadores:** Marko Bohanec y Blaz Zupan.
* **Fecha:** Junio de 1997.
* **Propósito Original:** Demostrar el funcionamiento de sistemas expertos de decisión (como DEX) y probar algoritmos de inducción estructural.
* **Número de Instancias:** 1,728 (el dataset cubre el 100% de las combinaciones posibles de los atributos).
* **Valores Faltantes:** Ninguno.

---

## 2. Estructura del Modelo

El dataset se basa en una jerarquía de decisión. Aunque el archivo final solo relaciona los atributos de entrada con la clase final, el modelo original sigue esta lógica:

| Nivel de Entrada | Concepto Intermedio | Objetivo Final (Target) |
| --- | --- | --- |
| `buying` (Precio de compra) | **PRICE** (Precio general) | **CAR** (Aceptabilidad) |
| `maint` (Mantenimiento) |  |  |
| `doors` (Puertas) | **COMFORT** (Confort) |  |
| `persons` (Capacidad) |  |  |
| `lug_boot` (Maletero) |  |  |
| `safety` (Seguridad) | **TECH** (Características Técnicas) |  |

---
# Cardinalidad y Dominio

## 3. Atributos (Variables de Entrada)

Todos los atributos son **nominales/ordinales**. Aquí están sus posibles valores:

| Atributo  | Descripción                     | Dominio                                   | Cardinalidad |
|-----------|----------------------------------|--------------------------------------------|--------------|
| buying    | Precio de compra                 | {v-high, high, med, low}                   | 4            |
| maint     | Precio de mantenimiento          | {v-high, high, med, low}                   | 4            |
| doors     | Número de puertas                | {2, 3, 4, 5, 6 donde 6 estaba definido como more                       | 4            |
| persons   | Capacidad de personas            | {2, 4, 5, donde 5 estaba definido como more                           | 3            |
| lug_boot  | Tamaño del maletero              | {small, med, big}                          | 3            |
| safety    | Seguridad estimada del auto      | {low, med, high}                           | 3            |
|-----------|----------------------------------|--------------------------------------------|--------------|
| **Total combinaciones posibles** |  |  | **1728 (4×4×4×3×3×3)** |
---

## 4. Distribución de la Columna Clase 

Cardilanidad 4

| Clase | Significado | Cantidad | Porcentaje |
| --- | --- | --- | --- |
| `unacc` | Inaceptable | 1210 | **70.02%** |
| `acc` | Aceptable | 384 | 22.22% |
| `good` | Bueno | 69 | 3.99% |
| `v-good` | Muy bueno | 65 | 3.76% |

---

In [64]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
from ucimlrepo import fetch_ucirepo 
  


# fetch dataset 
car_evaluation = fetch_ucirepo(id=19) 
  
# data (as pandas dataframes) 
X = car_evaluation.data.features 
y = car_evaluation.data.targets 
  
# metadata 
print(car_evaluation.metadata) 
  
# variable information 
print(car_evaluation.variables) 

df = pd.concat([car_evaluation.data.features, car_evaluation.data.targets], axis=1)

df.head()

{'uci_id': 19, 'name': 'Car Evaluation', 'repository_url': 'https://archive.ics.uci.edu/dataset/19/car+evaluation', 'data_url': 'https://archive.ics.uci.edu/static/public/19/data.csv', 'abstract': 'Derived from simple hierarchical decision model, this database may be useful for testing constructive induction and structure discovery methods.', 'area': 'Other', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 1728, 'num_features': 6, 'feature_types': ['Categorical'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1988, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5JP48', 'creators': ['Marko Bohanec'], 'intro_paper': {'ID': 249, 'type': 'NATIVE', 'title': 'Knowledge acquisition and explanation for multi-attribute decision making', 'authors': 'M. Bohanec, V. Rajkovič', 'venue': '8th Intl Workshop on Expert Systems and their Applications, Avignon, France', 'year': 1988, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/KNOWLEDGE-ACQUISITION-AND-EXPLANATION-FOR-DECISION-Bohanec-Rajkovi%C4%8D/8bab443ae322ff47c3e609272bd93fd4650555bc', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Car Evaluation Database was derived from a simple hierarchical decision model originally developed for the demonstration of DEX, M. Bohanec, V. Rajkovic: Expert system for decision making. Sistemica 1(1), pp. 145-157, 1990.). The model evaluates cars according to the following concept structure:\r\n\r\nCAR                      car acceptability\r\n. PRICE                  overall price\r\n. . buying               buying price\r\n. . maint                price of the maintenance\r\n. TECH                   technical characteristics\r\n. . COMFORT              comfort\r\n. . . doors              number of doors\r\n. . . persons            capacity in terms of persons to carry\r\n. . . lug_boot           the size of luggage boot\r\n. . safety               estimated safety of the car\r\n\r\nInput attributes are printed in lowercase. Besides the target concept (CAR), the model includes three intermediate concepts: PRICE, TECH, COMFORT. Every concept is in the original model related to its lower level descendants by a set of examples (for these examples sets see http://www-ai.ijs.si/BlazZupan/car.html).\r\n\r\nThe Car Evaluation Database contains examples with the structural information removed, i.e., directly relates CAR to the six input attributes: buying, maint, doors, persons, lug_boot, safety.\r\n\r\nBecause of known underlying concept structure, this database may be particularly useful for testing constructive induction and structure discovery methods.\r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'buying:   vhigh, high, med, low.\nmaint:    vhigh, high, med, low.\ndoors:    2, 3, 4, 5more.\npersons:  2, 4, more.\nlug_boot: small, med, big.\nsafety:   low, med, high.', 'citation': None}}
       name     role         type demographic  \
0    buying  Feature  Categorical        None
1     maint  Feature  Categorical        None
2     doors  Feature  Categorical        None
3   persons  Feature  Categorical        None
4  lug_boot  Feature  Categorical        None
5    safety  Feature  Categorical        None
6     class   Target  Categorical        None

                                         description units missing_values
0                                       buying price  None             no
1                           price of the maintenance  None             no
2                                    number of doors  None             no
3              capacity in terms of persons to carry  None             no
4                           the size of luggage boot  None             no
5                        estimated safety of the car  None             no
6  evaulation level (unacceptable, acceptable, go...  None             no

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [65]:

print("Tipo de datos por columna:")
df.info()


print("-"*60)
print("Numero de valores unicos por columna:")
print(df.nunique())

Tipo de datos por columna:
<class 'pandas.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   str
 1   maint     1728 non-null   str
 2   doors     1728 non-null   str
 3   persons   1728 non-null   str
 4   lug_boot  1728 non-null   str
 5   safety    1728 non-null   str
 6   class     1728 non-null   str
dtypes: str(7)
memory usage: 94.6 KB
------------------------------------------------------------
Numero de valores unicos por columna:
buying      4
maint       4
doors       4
persons     3
lug_boot    3
safety      3
class       4
dtype: int64

In [66]:
print("Numero de instancias por clase | porcentaje:")
print(df['class'].value_counts())
print(df['class'].value_counts(normalize=True))

Numero de instancias por clase | porcentaje:
class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64
class
unacc    0.700231
acc      0.222222
good     0.039931
vgood    0.037616
Name: proportion, dtype: float64

In [67]:
print("-"*60)
print("Numero de Valores nulos por columna:")
print(df.isnull().sum())

print("-"*60)
print("Total de filas:", len(df))

print("-"*60)
df.describe(include='all')

------------------------------------------------------------
Numero de Valores nulos por columna:
buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64
------------------------------------------------------------
Total de filas: 1728
------------------------------------------------------------

       buying  maint doors persons lug_boot safety  class
count    1728   1728  1728    1728     1728   1728   1728
unique      4      4     4       3        3      3      4
top     vhigh  vhigh     2       2    small    low  unacc
freq      432    432   432     576      576    576   1210

In [68]:

# Reemplazar los valores de la columna doors a español
df['doors'] = df['doors'].replace({2: 'dos', 3: 'tres', 4: 'cuatro', 5: 'cinco'})

# Traducir los valores de la columna maint a español
df['maint'] = df['maint'].replace({'vhigh': 'muy alto', 'high': 'alto', 'med': 'medio', 'low': 'bajo'})

# Traducir los valores de la columna buying a español
df['buying'] = df['buying'].replace({'vhigh': 'muy alto', 'high': 'alto', 'med': 'medio', 'low': 'bajo'})

# Traducir los valores de la columna lug_boot a español
df['lug_boot'] = df['lug_boot'].replace({'small': 'pequeño', 'med': 'medio', 'big': 'grande'})

# Traducir los valores de la columna safety a español
df['safety'] = df['safety'].replace({'low': 'bajo', 'med': 'medio', 'high': 'alto'})

df.head()

     buying     maint doors persons lug_boot safety  class
0  muy alto  muy alto     2       2  pequeño   bajo  unacc
1  muy alto  muy alto     2       2  pequeño  medio  unacc
2  muy alto  muy alto     2       2  pequeño   alto  unacc
3  muy alto  muy alto     2       2    medio   bajo  unacc
4  muy alto  muy alto     2       2    medio  medio  unacc

In [69]:
# Exportar en la carpeta carEvaluation los archivos csv
df.head(10).to_csv('carEvaluation/car_evaluation_10.csv', index=False)
df.head(100).to_csv('carEvaluation/car_evaluation_100.csv', index=False)
df.head(1000).to_csv('carEvaluation/car_evaluation_1000.csv', index=False)
df.to_csv('carEvaluation/car_evaluation_all.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'carEvaluation'